Gede Indra Adi Brata - 225150200111006

In [51]:
import numpy as np

In [52]:
L_input = np.array([
    [1, -1, -1],
    [1, -1, -1],
    [1, 1, 1]
])

U_input = np.array([
    [1, -1, 1],
    [1, -1, 1],
    [1, 1, 1]
])

L_input = L_input.flatten()
U_input = U_input.flatten()

Y_L = 1
Y_U = -1

weights = np.zeros(9)
bias = 0


def hebbian_learning(input_pattern, output, weights, bias):
    delta_weights = input_pattern * output
    weights += delta_weights
    

    bias += output
    
    return weights, bias


weights, bias = hebbian_learning(L_input, Y_L, weights, bias)
weights, bias = hebbian_learning(U_input, Y_U, weights, bias)

print("Nilai bobot setelah pelatihan:\n", weights)
print("Nilai bias setelah pelatihan:\n", bias)



Nilai bobot setelah pelatihan:
 [ 0.  0. -2.  0.  0. -2.  0.  0.  0.]
Nilai bias setelah pelatihan:
 0


Berapa nilai dari setiap bobot dan bias pada arsitekur hebb net setelah
melalui proses pelatihan menggunakan data tersebut ?

Nilai bobot setelah pelatihan:
 [ 0.  0. -2.  0.  0. -2.  0.  0.  0.]
Nilai bias setelah pelatihan:
 0

Apakah termasuk golongan “L” atau “U” untuk setiap data berikut ketika
diinputkan pada arsitektur hebb net ?

In [53]:
def activate(input_pattern, weights, bias):
    activation = np.dot(input_pattern, weights) + bias
    
    return np.where(activation >= 0, 1, -1)

In [54]:
I_input = np.array([
    [1, 1, 1],
    [-1, 1, -1],
    [1, 1, 1]
])

O_input = np.array([
    [1, 1, 1],
    [1, -1, 1],
    [1, 1, 1]
])

I_input = L_input.flatten()
O_input = U_input.flatten()

In [55]:
I_output = activate(I_input, weights, bias)
O_output = activate(O_input, weights, bias)

print("Output untuk I_input:", I_output)
print("Output untuk O_input:", O_output)

Output untuk I_input: 1
Output untuk O_input: -1


Sehingga data I termasuk golongan L dan data O termasuk golongan U

In [56]:
L_input = np.array([
    [1, -1, -1],
    [1, -1, -1],
    [1, 1, 1]
])

U_input = np.array([
    [1, -1, 1],
    [1, -1, 1],
    [1, 1, 1]
])

L_input = L_input.flatten()
U_input = U_input.flatten()
L_target = 1
U_target = -1


In [57]:
def hebbian_network(inputs, target):
  weights = np.zeros(9)
  bias = 0
  
  for i, input in enumerate(inputs):
    for j, x in enumerate(input):
      weights[j] += x * target[i]
    
    bias += target[i]
    
  return weights, bias

In [58]:
weights, bias = hebbian_network([L_input, U_input], [L_target, U_target])
print("Nilai bobot setelah pelatihan:\n", weights)
print("Nilai bias setelah pelatihan:\n", bias)

Nilai bobot setelah pelatihan:
 [ 0.  0. -2.  0.  0. -2.  0.  0.  0.]
Nilai bias setelah pelatihan:
 0
