# Bab 8 Backpropagation (1)

## Praktikum

### a) Fungsi *Binary Encoding* dan *Decoding*

Tulis kode ke dalam *cell* di bawah ini:

In [12]:
def bin_enc(lbl):
  mi = min(lbl)
  length = len(bin(max(lbl) - mi + 1)[2:])
  enc = []
  for i in lbl:
    b = bin(i - mi)[2:].zfill(length)
    enc.append([int(n) for n in b])
  
  return enc

def bin_dec(enc, mi=0):
  lbl = []
  for e in enc:
    rounded = [int(round(x)) for x in e]
    string = ''.join(str(x) for x in rounded)
    num = int(string, 2) + mi
    lbl.append(num)
  
  return lbl

### b) Percobaan *Binary Encoding* dan *Decoding*

Tulis kode ke dalam *cell* di bawah ini:

In [13]:
labels = 1, 2, 3, 4
enc = bin_enc(labels)
dec = bin_dec(enc, min(labels))
print(enc) 
print(dec)

[[0, 0, 0], [0, 0, 1], [0, 1, 0], [0, 1, 1]]
[1, 2, 3, 4]


### c) Fungsi *One-hot Encoding* dan *Decoding*

Tulis kode ke dalam *cell* di bawah ini:


In [14]:
import numpy as np
def onehot_enc(lbl, min_val=0):
  mi = min(lbl)
  enc = np.full((len(lbl), max(lbl) - mi + 1), min_val, np.int8)
  for i, x in enumerate(lbl):
    enc[i, x - mi] = 1
  
  return enc

def onehot_dec(enc, mi=0):
  return [np.argmax(e) + mi for e in enc]

### d) Percobaan *One Hot Encoding* dan *Decoding*

Tulis kode ke dalam *cell* di bawah ini:

In [15]:
labels = 1, 2, 3, 4
enc = onehot_enc(labels)
dec = onehot_dec(enc, min(labels))
print(enc)
print(dec)

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]
[1, 2, 3, 4]


### e) Fungsi Aktivasi Sigmoid dan Derivatifnya

Tulis kode ke dalam *cell* di bawah ini:

In [16]:
def sig(X):
  return [1 / (1 + np.exp(-x)) for x in X]

def sigd(X):
  output = []
  for i, x in enumerate(X):
    s = sig([x])[0]
    output.append(s * (1 - s))
  
  return output

In [17]:
import pandas as pd

df = pd.read_csv("iris.csv")
df.tail()

sepal.length  sepal.width  petal.length  petal.width    variety
145           6.7          3.0           5.2          2.3  Virginica
146           6.3          2.5           5.0          1.9  Virginica
147           6.5          3.0           5.2          2.0  Virginica
148           6.2          3.4           5.4          2.3  Virginica
149           5.9          3.0           5.1          1.8  Virginica

In [18]:
kelas = df["variety"]
kelas

0         Setosa
1         Setosa
2         Setosa
3         Setosa
4         Setosa
         ...    
145    Virginica
146    Virginica
147    Virginica
148    Virginica
149    Virginica
Name: variety, Length: 150, dtype: object

In [28]:
def bin_enc_str(strings):
  unique_strings = list(set(strings))
  unique_strings.sort()
  str_to_bin = {s: bin(i)[2:].zfill(len(bin(len(unique_strings) - 1)[2:])) for i, s in enumerate(unique_strings)}
  enc = [[int(bit) for bit in str_to_bin[s]] for s in strings]
  return enc, str_to_bin

def bin_dec_str(enc, str_to_bin):
  bin_to_str = {v: k for k, v in str_to_bin.items()}
  dec = [''.join(map(str, bits)) for bits in enc]
  return [bin_to_str[b] for b in dec]


bin_enc_kelas, str_to_bin = bin_enc_str(kelas)
bin_enc_kelas[0:5]

[[0, 0], [0, 0], [0, 0], [0, 0], [0, 0]]

In [29]:
bin_dec_kelas = bin_dec_str(bin_enc_kelas, str_to_bin)
bin_dec_kelas[0:5]

['Setosa', 'Setosa', 'Setosa', 'Setosa', 'Setosa']

In [30]:
def onehot_enc_str(strings):
  unique_strings = sorted(set(strings))
  str_to_index = {s: i for i, s in enumerate(unique_strings)}
  enc = np.zeros((len(strings), len(unique_strings)), dtype=int)
  for i, s in enumerate(strings):
    enc[i, str_to_index[s]] = 1
  return enc, str_to_index

def onehot_dec_str(enc, str_to_index):
  index_to_str = {i: s for s, i in str_to_index.items()}
  dec = [index_to_str[np.argmax(row)] for row in enc]
  return dec


one_hot_enc_kelas, str_to_index = onehot_enc_str(kelas)
one_hot_enc_kelas[0:5]

array([[1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0]])

In [31]:
one_hot_dec_kelas = onehot_dec_str(one_hot_enc_kelas, str_to_index)
one_hot_dec_kelas[0:5]

['Setosa', 'Setosa', 'Setosa', 'Setosa', 'Setosa']